export const PATH = {
  newBlock: '/blocks/new',
  savedBlock: '/blocks/saved',
  dailyDiary: '/dailyDiary',
  home: '/home',
  myProfile: '/profile',
  editProfile: '/profile/edit',
  myProfileSettings: '/profile/settings',
  newProfile: '/profiles/new',
  newProfileDone: '/profiles/new/done',
  signUpAgreements: '/profiles/new/agreements',
  agreements: '/agreements',
  login: '/login',
  loginCallback: '/login/callback',
}
